# Generated by Django 4.2.13 on 2024-05-26 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("protocolApplication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caloriedetail",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=1716683264,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskdetails",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                default=1716683264,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
