import { c as create_ssr_component, d as add_attribute } from "../../../../chunks/ssr.js";
const css = {
  code: "@keyframes svelte-n6kr07-gradientAnimation{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}.animated-background.svelte-n6kr07{background:linear-gradient(270deg, #ff7e5f, #feb47b);background-size:400% 400%;animation:svelte-n6kr07-gradientAnimation 15s ease infinite}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<script>\\r\\n\\r\\n    let queryForVideos = \'\';\\r\\n\\r\\n    async function handleVideos(){\\r\\n\\r\\n        document.getElementById(\\"returnedVideos\\").innerHTML = ``;\\r\\n\\r\\n        console.log(queryForVideos)\\r\\n\\r\\n        fetch(\'https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=5&q=\' + queryForVideos + \'&type=video&key=AIzaSyA20OFgpO9qgwShY_S5PBzh3_Uw2-o3v4k\')\\r\\n        .then(result => result.json())\\r\\n        .then(data=>{\\r\\n           console.log(data)\\r\\n           data.items.forEach(a => {\\r\\n               document.getElementById(\\"returnedVideos\\").innerHTML += `\\r\\n               <p class=\\"card-text\\">\\r\\n               <a href=\\"https://www.youtube.com/watch?v=${a.id.videoId}\\" class=\\"yt-=video\\">\\r\\n                   <img src=\\"${a.snippet.thumbnails.high.url}\\"/>\\r\\n                   <h3>${a.snippet.title}</h3>\\r\\n               </a>\\r\\n               </p><br><br>\\r\\n               `\\r\\n           })\\r\\n        })\\r\\n\\r\\n    }\\r\\n\\r\\n<\/script>\\r\\n\\r\\n<style>\\r\\n\\r\\n@keyframes gradientAnimation {\\r\\n    0% {\\r\\n        background-position: 0% 50%;\\r\\n    }\\r\\n    50% {\\r\\n        background-position: 100% 50%;\\r\\n    }\\r\\n    100% {\\r\\n        background-position: 0% 50%;\\r\\n    }\\r\\n}\\r\\n\\r\\n.animated-background {\\r\\n    background: linear-gradient(270deg, #ff7e5f, #feb47b);\\r\\n    background-size: 400% 400%;\\r\\n    animation: gradientAnimation 15s ease infinite;\\r\\n}\\r\\n\\r\\n</style>\\r\\n\\r\\n<div class=\\"p-3 mb-2 bg-light text-dark rounded shadow-sm animated-background\\">\\r\\n  <h2 class=\\"my-4\\">Find exercise videos</h2>\\r\\n  <div class=\\"col-12 col-md-6\\">\\r\\n     <form on:submit|preventDefault={handleVideos}>\\r\\n         <label for=\\"queryForVideos\\">Enter the exercise videos that you want:</label>\\r\\n         <div class=\\"mb-3\\">\\r\\n             <input class=\\"form-control\\" type=\\"text\\" id=\\"queryForVideos\\" placeholder=\\"query\\" bind:value={queryForVideos}/>\\r\\n         </div>\\r\\n         <button class=\\"btn btn-primary\\" type=\\"submit\\">Fetch videos</button>\\r\\n     </form>\\r\\n  </div>\\r\\n  <br>\\r\\n  <br>\\r\\n</div>\\r\\n\\r\\n<div>\\r\\n   <div class=\\"card-body d-flex flex-column justify-content-between gap-4\\">\\r\\n        <div id=\\"returnedVideos\\" class=\\"row\\">\\r\\n        </div>\\r\\n   </div>\\r\\n</div>\\r\\n\\r\\n\\r\\n"],"names":[],"mappings":"AAgCA,WAAW,+BAAkB,CACzB,EAAG,CACC,mBAAmB,CAAE,EAAE,CAAC,GAC5B,CACA,GAAI,CACA,mBAAmB,CAAE,IAAI,CAAC,GAC9B,CACA,IAAK,CACD,mBAAmB,CAAE,EAAE,CAAC,GAC5B,CACJ,CAEA,kCAAqB,CACjB,UAAU,CAAE,gBAAgB,MAAM,CAAC,CAAC,OAAO,CAAC,CAAC,OAAO,CAAC,CACrD,eAAe,CAAE,IAAI,CAAC,IAAI,CAC1B,SAAS,CAAE,+BAAiB,CAAC,GAAG,CAAC,IAAI,CAAC,QAC1C"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let queryForVideos = "";
  $$result.css.add(css);
  return `<div class="p-3 mb-2 bg-light text-dark rounded shadow-sm animated-background svelte-n6kr07"><h2 class="my-4" data-svelte-h="svelte-sfhl57">Find exercise videos</h2> <div class="col-12 col-md-6"><form><label for="queryForVideos" data-svelte-h="svelte-k8w1ey">Enter the exercise videos that you want:</label> <div class="mb-3"><input class="form-control" type="text" id="queryForVideos" placeholder="query"${add_attribute("value", queryForVideos, 0)}></div> <button class="btn btn-primary" type="submit" data-svelte-h="svelte-xmc5on">Fetch videos</button></form></div> <br> <br></div> <div data-svelte-h="svelte-15b8uuq"><div class="card-body d-flex flex-column justify-content-between gap-4"><div id="returnedVideos" class="row"></div></div></div>`;
});
export {
  Page as default
};
